spring:
  application:
    name: center-server
  security:
    user:
      name: test
      password: test
eureka:
  server:
    enable-self-preservation: false
  instance:
    appname: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: gitlab.mengxiangjing.com
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 3030
